# Registration Relayer Configuration - LOCAL HARDHAT
# Points to Hardhat running on host machine (not in Docker)

log:
  level: debug
  disable_sentry: true

listener:
  addr: :8000

network:
  # Host Hardhat RPC (from Docker container: use host.docker.internal on macOS)
  rpc: "http://host.docker.internal:8545"

  # Registration2 PROXY address (NOT the implementation!)
  # The proxy has stateKeeper set and dispatchers registered
  registration: "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1"
  
  # StateKeeper PROXY address  
  lightweight_state: "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e"
  
  # Hardhat first default account private key (Account #0)
  # This account has 10000 ETH on local Hardhat
  private_key: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  
  # Gas settings
  gas_limit_multiplier: 1.2

  # Whitelist of allowed destination contracts (PROXY addresses)
  whitelist:
    - "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1"  # Registration2 Proxy
    - "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853"  # CertificatesSMT Proxy
    - "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707"  # RegistrationSMT Proxy

cop:
  disabled: true
