# Registration Relayer Configuration
# This service SENDS TRANSACTIONS to Rarimo L2
# 
# LOCAL DEV: Points to Hardhat node on host machine
# For testnet: switch rpc to https://l2.testnet.rarimo.com

log:
  level: debug
  disable_sentry: true

listener:
  addr: :8000

network:
  # LOCAL: Hardhat node on host machine (Docker needs host.docker.internal)
  rpc: "http://host.docker.internal:8545"
  
  # Registration2 contract address (from passport-contracts deployment - Jan 22, 2026 fresh)
  registration: "0x67d269191c92Caf3cD7723F116c85e6E9bf55933"
  
  # StateKeeper contract
  lightweight_state: "0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f"
  
  # Hardhat default account #0 (10000 ETH, for local testing only!)
  private_key: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  
  # Gas settings
  gas_limit_multiplier: 1.2
  
  # Whitelist of allowed destination contracts
  # Users can only send transactions to these addresses
  whitelist:
    - "0x67d269191c92Caf3cD7723F116c85e6E9bf55933"  # Registration2
    - "0x68B1D87F95878fE05B998F19b66F4baba5De1aed"  # CertificatesSMT
    - "0xc6e7DF5E7b4f2A278906862b61205850344D4e7d"  # RegistrationSMT

cop:
  disabled: true
