# Registration Relayer Configuration
# This service SENDS TRANSACTIONS to Rarimo L2
# 
# LOCAL DEV: Points to Hardhat node on host machine
# For testnet: switch rpc to https://l2.testnet.rarimo.com

log:
  level: debug
  disable_sentry: true

listener:
  addr: :8000

network:
  # LOCAL: Hardhat node on host machine (Docker needs host.docker.internal)
  rpc: "http://host.docker.internal:8545"
  
  # Registration2 contract address (from passport-contracts deployment - Jan 2025)
  registration: "0x04F339eC4D75Cf2833069e6e61b60eF56461CD7C"
  
  # StateKeeper contract
  lightweight_state: "0x6D712CB50297b97b79dE784d10F487C00d7f8c2C"
  
  # Hardhat default account #0 (10000 ETH, for local testing only!)
  private_key: "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  
  # Gas settings
  gas_limit_multiplier: 1.2
  
  # Whitelist of allowed destination contracts
  # Users can only send transactions to these addresses
  whitelist:
    - "0x04F339eC4D75Cf2833069e6e61b60eF56461CD7C"  # Registration2
    - "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"  # CertificatesSMT
    - "0x0165878A594ca255338adfa4d48449f69242Eb8F"  # RegistrationSMT

cop:
  disabled: true
